### model
model_name_or_path: /home/bingxing2/ailab/quyichang/zengyu/model/Qwen2.5-VL-3B-Instruct  # 1. 改Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144  # 512*512
video_max_pixels: 401408  # 
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: /home/bingxing2/ailab/quyichang/zengyu/code/LLaMA-Factory/examples/deepspeed/ds_z3_offload_config.json  # 2.改一下路径

### dataset
dataset: Temporal-RL-v1-SFT-data, Temporal-RL-v2-SFT-data  # 3. 不用改
dataset_dir: /home/bingxing2/ailab/quyichang/zhaoy/data/LLaMA-Factory-DATA  # 4.改一下路径
template: qwen2_vl
cutoff_len: 16384 # 7000
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /home/bingxing2/ailab/quyichang/zhaoy/models/Temporal-RL-v2-SFT-Model  # 5. 改一下路径
logging_steps: 1
save_steps: 50000
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 2.0  # 轮次
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

# FORCE_TORCHRUN=1 llamafactory-cli train examples/train_full/qwen2_5vl_full_sft.yaml
# export HF_ENDPOINT=https://hf-mirror.com
# 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

# huggingface-cli upload YuZeng260/puzzle /home/bingxing2/ailab/quyichang/zengyu/data/puzzle --repo-type=dataset